use crate::tlv::element_type::ElementType;

///
/// @author Mihael Berčič
/// @date 24. 9. 24
///
pub enum GlobalStatusCode {
    Success = 0x00,
    Failure = 0x01,
    InvalidSubscription = 0x7D,
    UnsupportedAccess = 0x7E,
    UnsupportedEndpoint = 0x7F,
    InvalidAction = 0x80,
    UnsupportedCommand = 0x81,
    InvalidCommand = 0x85,
    UnsupportedAttribute = 0x86,
    ConstraintError = 0x87,
    UnsupportedWrite = 0x88,
    ResourceExhausted = 0x89,
    NotFound = 0x8B,
    UnreportableAttribute = 0x8C,
    InvalidDataType = 0x8D,
    UnsupportedRead = 0x8F,
    DataVersionMismatch = 0x92,
    Timeout = 0x93,
    UnsupportedNode = 0x9B,
    Busy = 0x9C,
    UnsupportedCluster = 0xC3,
    NoUpstreamSubscription = 0xC5,
    NeedsTimedInteraction = 0xC6,
    UnsupportedEvent = 0xC7,
    PathsExhausted = 0xC8,
    TimedRequestMismatch = 0xC9,
    FailsafeRequired = 0xCA,
    InvalidInState = 0xCB,
}

#[derive(Clone, Debug)]
pub enum QueryParameter<T> {
    Wildcard,
    Specific(T),
}

#[derive(Eq, Hash, PartialEq, Clone, Copy, Debug)]
#[repr(u32)]
pub enum ClusterID {
    AccessControl = 0x001F,
    AccountLogin = 0x050E,
    Actions = 0x0025,
    ActivatedCarbonFilterMonitoring = 0x0072,
    AdministratorCommissioning = 0x003C,
    AirQuality = 0x005B,
    ApplicationBasic = 0x050D,
    ApplicationLauncher = 0x050C,
    AudioOutput = 0x050B,
    BallastConfiguration = 0x0301,
    BasicInformation = 0x0028,
    Binding = 0x001E,
    BooleanState = 0x0045,
    BooleanStateConfiguration = 0x0080,
    BridgedDeviceBasicInformation = 0x0039,
    CarbonDioxideConcentrationMeasurement = 0x040D,
    CarbonMonoxideConcentrationMeasurement = 0x040C,
    Channel = 0x0504,
    ColorControl = 0x0300,
    ContentAppObserver = 0x0510,
    ContentControl = 0x050F,
    ContentLauncher = 0x050A,
    Descriptor = 0x001D,
    DeviceEnergyManagement = 0x0098,
    DeviceEnergyManagementMode = 0x009F,
    DiagnosticLogs = 0x0032,
    DishwasherAlarm = 0x005D,
    DishwasherMode = 0x0059,
    DoorLock = 0x0101,
    ElectricalEnergyMeasurement = 0x0091,
    ElectricalPowerMeasurement = 0x0090,
    EnergyEvse = 0x0099,
    EnergyEvseMode = 0x009D,
    EnergyPreference = 0x009B,
    EthernetNetworkDiagnostics = 0x0037,
    FanControl = 0x0202,
    FixedLabel = 0x0040,
    FlowMeasurement = 0x0404,
    FormaldehydeConcentrationMeasurement = 0x042B,
    GeneralCommissioning = 0x0030,
    GeneralDiagnostics = 0x0033,
    GroupKeyManagement = 0x003F,
    Groups = 0x0004,
    HepaFilterMonitoring = 0x0071,
    IcdManagement = 0x0046,
    Identify = 0x0003,
    IlluminanceMeasurement = 0x0400,
    KeypadInput = 0x0509,
    LaundryDryerControls = 0x004A,
    LaundryWasherControls = 0x0053,
    LaundryWasherMode = 0x0051,
    LevelControl = 0x0008,
    LocalizationConfiguration = 0x002B,
    LowPower = 0x0508,
    MediaInput = 0x0507,
    MediaPlayback = 0x0506,
    Messages = 0x0097,
    MicrowaveOvenControl = 0x005F,
    MicrowaveOvenMode = 0x005E,
    ModeSelect = 0x0050,
    NetworkCommissioning = 0x0031,
    NitrogenDioxideConcentrationMeasurement = 0x0413,
    OccupancySensing = 0x0406,
    OnOff = 0x0006,
    OperationalCredentials = 0x003E,
    OperationalState = 0x0060,
    OtaSoftwareUpdateProvider = 0x0029,
    OtaSoftwareUpdateRequester = 0x002A,
    OvenCavityOperationalState = 0x0048,
    OvenMode = 0x0049,
    OzoneConcentrationMeasurement = 0x0415,
    Pm10ConcentrationMeasurement = 0x042D,
    Pm1ConcentrationMeasurement = 0x042C,
    Pm25ConcentrationMeasurement = 0x042A,
    PowerSource = 0x002F,
    PowerSourceConfiguration = 0x002E,
    PowerTopology = 0x009C,
    PressureMeasurement = 0x0403,
    ProxyConfiguration = 0x0042,
    ProxyDiscovery = 0x0043,
    PulseWidthModulation = 0x001C,
    PumpConfigurationAndControl = 0x0200,
    RadonConcentrationMeasurement = 0x042F,
    RefrigeratorAlarm = 0x0057,
    RefrigeratorAndTemperatureControlledCabinetMode = 0x0052,
    RelativeHumidityMeasurement = 0x0405,
    RvcCleanMode = 0x0055,
    RvcOperationalState = 0x0061,
    RvcRunMode = 0x0054,
    ScenesManagement = 0x0062,
    SmokeCoAlarm = 0x005C,
    SoftwareDiagnostics = 0x0034,
    Switch = 0x003B,
    TargetNavigator = 0x0505,
    TemperatureControl = 0x0056,
    TemperatureMeasurement = 0x0402,
    Thermostat = 0x0201,
    ThermostatUserInterfaceConfiguration = 0x0204,
    ThreadNetworkDiagnostics = 0x0035,
    TimeFormatLocalization = 0x002C,
    TimeSynchronization = 0x0038,
    TotalVolatileOrganicCompoundsConcentrationMeasurement = 0x042E,
    UnitLocalization = 0x002D,
    UserLabel = 0x0041,
    ValidProxies = 0x0044,
    ValveConfigurationAndControl = 0x0081,
    WakeOnLan = 0x0503,
    WiFiNetworkDiagnostics = 0x0036,
    WindowCovering = 0x0102,
}

impl From<u32> for ClusterID {
    fn from(value: u32) -> Self {
        match value {
            0x001F => ClusterID::AccessControl,
            0x050E => ClusterID::AccountLogin,
            0x0025 => ClusterID::Actions,
            0x0072 => ClusterID::ActivatedCarbonFilterMonitoring,
            0x003C => ClusterID::AdministratorCommissioning,
            0x005B => ClusterID::AirQuality,
            0x050D => ClusterID::ApplicationBasic,
            0x050C => ClusterID::ApplicationLauncher,
            0x050B => ClusterID::AudioOutput,
            0x0301 => ClusterID::BallastConfiguration,
            0x0028 => ClusterID::BasicInformation,
            0x001E => ClusterID::Binding,
            0x0045 => ClusterID::BooleanState,
            0x0080 => ClusterID::BooleanStateConfiguration,
            0x0039 => ClusterID::BridgedDeviceBasicInformation,
            0x040D => ClusterID::CarbonDioxideConcentrationMeasurement,
            0x040C => ClusterID::CarbonMonoxideConcentrationMeasurement,
            0x0504 => ClusterID::Channel,
            0x0300 => ClusterID::ColorControl,
            0x0510 => ClusterID::ContentAppObserver,
            0x050F => ClusterID::ContentControl,
            0x050A => ClusterID::ContentLauncher,
            0x001D => ClusterID::Descriptor,
            0x0098 => ClusterID::DeviceEnergyManagement,
            0x009F => ClusterID::DeviceEnergyManagementMode,
            0x0032 => ClusterID::DiagnosticLogs,
            0x005D => ClusterID::DishwasherAlarm,
            0x0059 => ClusterID::DishwasherMode,
            0x0101 => ClusterID::DoorLock,
            0x0091 => ClusterID::ElectricalEnergyMeasurement,
            0x0090 => ClusterID::ElectricalPowerMeasurement,
            0x0099 => ClusterID::EnergyEvse,
            0x009D => ClusterID::EnergyEvseMode,
            0x009B => ClusterID::EnergyPreference,
            0x0037 => ClusterID::EthernetNetworkDiagnostics,
            0x0202 => ClusterID::FanControl,
            0x0040 => ClusterID::FixedLabel,
            0x0404 => ClusterID::FlowMeasurement,
            0x042B => ClusterID::FormaldehydeConcentrationMeasurement,
            0x0030 => ClusterID::GeneralCommissioning,
            0x0033 => ClusterID::GeneralDiagnostics,
            0x003F => ClusterID::GroupKeyManagement,
            0x0004 => ClusterID::Groups,
            0x0071 => ClusterID::HepaFilterMonitoring,
            0x0046 => ClusterID::IcdManagement,
            0x0003 => ClusterID::Identify,
            0x0400 => ClusterID::IlluminanceMeasurement,
            0x0509 => ClusterID::KeypadInput,
            0x004A => ClusterID::LaundryDryerControls,
            0x0053 => ClusterID::LaundryWasherControls,
            0x0051 => ClusterID::LaundryWasherMode,
            0x0008 => ClusterID::LevelControl,
            0x002B => ClusterID::LocalizationConfiguration,
            0x0508 => ClusterID::LowPower,
            0x0507 => ClusterID::MediaInput,
            0x0506 => ClusterID::MediaPlayback,
            0x0097 => ClusterID::Messages,
            0x005F => ClusterID::MicrowaveOvenControl,
            0x005E => ClusterID::MicrowaveOvenMode,
            0x0050 => ClusterID::ModeSelect,
            0x0031 => ClusterID::NetworkCommissioning,
            0x0413 => ClusterID::NitrogenDioxideConcentrationMeasurement,
            0x0406 => ClusterID::OccupancySensing,
            0x0006 => ClusterID::OnOff,
            0x003E => ClusterID::OperationalCredentials,
            0x0060 => ClusterID::OperationalState,
            0x0029 => ClusterID::OtaSoftwareUpdateProvider,
            0x002A => ClusterID::OtaSoftwareUpdateRequester,
            0x0048 => ClusterID::OvenCavityOperationalState,
            0x0049 => ClusterID::OvenMode,
            0x0415 => ClusterID::OzoneConcentrationMeasurement,
            0x042D => ClusterID::Pm10ConcentrationMeasurement,
            0x042C => ClusterID::Pm1ConcentrationMeasurement,
            0x042A => ClusterID::Pm25ConcentrationMeasurement,
            0x002F => ClusterID::PowerSource,
            0x002E => ClusterID::PowerSourceConfiguration,
            0x009C => ClusterID::PowerTopology,
            0x0403 => ClusterID::PressureMeasurement,
            0x0042 => ClusterID::ProxyConfiguration,
            0x0043 => ClusterID::ProxyDiscovery,
            0x001C => ClusterID::PulseWidthModulation,
            0x0200 => ClusterID::PumpConfigurationAndControl,
            0x042F => ClusterID::RadonConcentrationMeasurement,
            0x0057 => ClusterID::RefrigeratorAlarm,
            0x0052 => ClusterID::RefrigeratorAndTemperatureControlledCabinetMode,
            0x0405 => ClusterID::RelativeHumidityMeasurement,
            0x0055 => ClusterID::RvcCleanMode,
            0x0061 => ClusterID::RvcOperationalState,
            0x0054 => ClusterID::RvcRunMode,
            0x0062 => ClusterID::ScenesManagement,
            0x005C => ClusterID::SmokeCoAlarm,
            0x0034 => ClusterID::SoftwareDiagnostics,
            0x003B => ClusterID::Switch,
            0x0505 => ClusterID::TargetNavigator,
            0x0056 => ClusterID::TemperatureControl,
            0x0402 => ClusterID::TemperatureMeasurement,
            0x0201 => ClusterID::Thermostat,
            0x0204 => ClusterID::ThermostatUserInterfaceConfiguration,
            0x0035 => ClusterID::ThreadNetworkDiagnostics,
            0x002C => ClusterID::TimeFormatLocalization,
            0x0038 => ClusterID::TimeSynchronization,
            0x042E => ClusterID::TotalVolatileOrganicCompoundsConcentrationMeasurement,
            0x002D => ClusterID::UnitLocalization,
            0x0041 => ClusterID::UserLabel,
            0x0044 => ClusterID::ValidProxies,
            0x0081 => ClusterID::ValveConfigurationAndControl,
            0x0503 => ClusterID::WakeOnLan,
            0x0036 => ClusterID::WiFiNetworkDiagnostics,
            0x0102 => ClusterID::WindowCovering,
            _ => panic!("Unknown cluster id: 0x{:04x}", value),
        }
    }
}

#[repr(u8)]
#[derive(Debug, Eq, PartialEq, Clone)]
pub enum InteractionProtocolOpcode {
    StatusResponse = 0x01,
    ReadRequest = 0x02,
    SubscribeRequest = 0x03,
    SubscribeResponse = 0x04,
    ReportData = 0x05,
    WriteRequest = 0x06,
    WriteResponse = 0x07,
    InvokeRequest = 0x08,
    InvokeResponse = 0x09,
    TimedRequest = 0x0A,
}

impl From<u8> for InteractionProtocolOpcode {
    fn from(value: u8) -> Self {
        match value {
            0x01 => InteractionProtocolOpcode::StatusResponse,
            0x02 => InteractionProtocolOpcode::ReadRequest,
            0x03 => InteractionProtocolOpcode::SubscribeRequest,
            0x04 => InteractionProtocolOpcode::SubscribeResponse,
            0x05 => InteractionProtocolOpcode::ReportData,
            0x06 => InteractionProtocolOpcode::WriteRequest,
            0x07 => InteractionProtocolOpcode::WriteResponse,
            0x08 => InteractionProtocolOpcode::InvokeRequest,
            0x09 => InteractionProtocolOpcode::InvokeResponse,
            0x0A => InteractionProtocolOpcode::TimedRequest,
            _ => panic!("Unknown Interaction Opcode"),
        }
    }
}

#[repr(u8)]
#[derive(Clone)]
pub enum StartUpOnOffEnum {
    Off = 0,
    On = 1,
    Toggle = 2,
}

impl From<StartUpOnOffEnum> for ElementType {
    fn from(value: StartUpOnOffEnum) -> Self {
        (value as u8).into()
    }
}
