[package]
name = "matter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p256 = { version = "0.13.2", features = ["ecdh", "ecdsa"] }
drbg = "0.2.0"
rand = "0.9.0-alpha.0"
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
hkdf = "0.12.3"
ccm = "0.5.0"
aes = "0.8.4"
